// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: service/channel_service.proto

package service

import (
	entity "github.com/Sujin1135/channel-collector-interface/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChannelsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	YoutubeHandles []string               `protobuf:"bytes,1,rep,name=youtube_handles,json=youtubeHandles,proto3" json:"youtube_handles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetChannelsRequest) Reset() {
	*x = GetChannelsRequest{}
	mi := &file_service_channel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsRequest) ProtoMessage() {}

func (x *GetChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_channel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelsRequest) Descriptor() ([]byte, []int) {
	return file_service_channel_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetChannelsRequest) GetYoutubeHandles() []string {
	if x != nil {
		return x.YoutubeHandles
	}
	return nil
}

type GetChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GetChannelsResponse_Data_
	//	*GetChannelsResponse_Error_
	Value         isGetChannelsResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse) Reset() {
	*x = GetChannelsResponse{}
	mi := &file_service_channel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse) ProtoMessage() {}

func (x *GetChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_channel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return file_service_channel_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetChannelsResponse) GetValue() isGetChannelsResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetChannelsResponse) GetData() *GetChannelsResponse_Data {
	if x != nil {
		if x, ok := x.Value.(*GetChannelsResponse_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *GetChannelsResponse) GetError() *GetChannelsResponse_Error {
	if x != nil {
		if x, ok := x.Value.(*GetChannelsResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isGetChannelsResponse_Value interface {
	isGetChannelsResponse_Value()
}

type GetChannelsResponse_Data_ struct {
	Data *GetChannelsResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GetChannelsResponse_Error_ struct {
	Error *GetChannelsResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetChannelsResponse_Data_) isGetChannelsResponse_Value() {}

func (*GetChannelsResponse_Error_) isGetChannelsResponse_Value() {}

type GetChannelsResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *entity.Channel        `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse_Data) Reset() {
	*x = GetChannelsResponse_Data{}
	mi := &file_service_channel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse_Data) ProtoMessage() {}

func (x *GetChannelsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_service_channel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse_Data.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse_Data) Descriptor() ([]byte, []int) {
	return file_service_channel_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetChannelsResponse_Data) GetChannel() *entity.Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type GetChannelsResponse_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*GetChannelsResponse_Error_BadRequest
	Error         isGetChannelsResponse_Error_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse_Error) Reset() {
	*x = GetChannelsResponse_Error{}
	mi := &file_service_channel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse_Error) ProtoMessage() {}

func (x *GetChannelsResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_channel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse_Error.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_channel_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetChannelsResponse_Error) GetError() isGetChannelsResponse_Error_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetChannelsResponse_Error) GetBadRequest() *entity.BadRequestError {
	if x != nil {
		if x, ok := x.Error.(*GetChannelsResponse_Error_BadRequest); ok {
			return x.BadRequest
		}
	}
	return nil
}

type isGetChannelsResponse_Error_Error interface {
	isGetChannelsResponse_Error_Error()
}

type GetChannelsResponse_Error_BadRequest struct {
	BadRequest *entity.BadRequestError `protobuf:"bytes,1,opt,name=bad_request,json=badRequest,proto3,oneof"`
}

func (*GetChannelsResponse_Error_BadRequest) isGetChannelsResponse_Error_Error() {}

var File_service_channel_service_proto protoreflect.FileDescriptor

var file_service_channel_service_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x14, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x79, 0x6f, 0x75, 0x74, 0x75,
	0x62, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x79, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x22, 0xb8, 0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x48, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x1a, 0x45, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x62,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x78, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x29, 0x2e, 0x69,
	0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x60, 0x0a, 0x22, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x75, 0x6a, 0x69, 0x6e, 0x31,
	0x31, 0x33, 0x35, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2d, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_service_channel_service_proto_rawDescOnce sync.Once
	file_service_channel_service_proto_rawDescData []byte
)

func file_service_channel_service_proto_rawDescGZIP() []byte {
	file_service_channel_service_proto_rawDescOnce.Do(func() {
		file_service_channel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_channel_service_proto_rawDesc), len(file_service_channel_service_proto_rawDesc)))
	})
	return file_service_channel_service_proto_rawDescData
}

var file_service_channel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_channel_service_proto_goTypes = []any{
	(*GetChannelsRequest)(nil),        // 0: io.contents.collector.GetChannelsRequest
	(*GetChannelsResponse)(nil),       // 1: io.contents.collector.GetChannelsResponse
	(*GetChannelsResponse_Data)(nil),  // 2: io.contents.collector.GetChannelsResponse.Data
	(*GetChannelsResponse_Error)(nil), // 3: io.contents.collector.GetChannelsResponse.Error
	(*entity.Channel)(nil),            // 4: io.contents.collector.Channel
	(*entity.BadRequestError)(nil),    // 5: BadRequestError
}
var file_service_channel_service_proto_depIdxs = []int32{
	2, // 0: io.contents.collector.GetChannelsResponse.data:type_name -> io.contents.collector.GetChannelsResponse.Data
	3, // 1: io.contents.collector.GetChannelsResponse.error:type_name -> io.contents.collector.GetChannelsResponse.Error
	4, // 2: io.contents.collector.GetChannelsResponse.Data.channel:type_name -> io.contents.collector.Channel
	5, // 3: io.contents.collector.GetChannelsResponse.Error.bad_request:type_name -> BadRequestError
	0, // 4: io.contents.collector.ChannelService.GetChannels:input_type -> io.contents.collector.GetChannelsRequest
	1, // 5: io.contents.collector.ChannelService.GetChannels:output_type -> io.contents.collector.GetChannelsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_channel_service_proto_init() }
func file_service_channel_service_proto_init() {
	if File_service_channel_service_proto != nil {
		return
	}
	file_service_channel_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GetChannelsResponse_Data_)(nil),
		(*GetChannelsResponse_Error_)(nil),
	}
	file_service_channel_service_proto_msgTypes[3].OneofWrappers = []any{
		(*GetChannelsResponse_Error_BadRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_channel_service_proto_rawDesc), len(file_service_channel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_channel_service_proto_goTypes,
		DependencyIndexes: file_service_channel_service_proto_depIdxs,
		MessageInfos:      file_service_channel_service_proto_msgTypes,
	}.Build()
	File_service_channel_service_proto = out.File
	file_service_channel_service_proto_goTypes = nil
	file_service_channel_service_proto_depIdxs = nil
}
